---
name: Build and Push Golang Image to AWS ECR
on:
  push:
   branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker
        CURRENT_VERSION: v1.0.0
        
        arr: (${string//"IMAGE_TAG"/ })
        VNUM1: ${IMAGE_TAG[0]}
        VNUM2: ${IMAGE_TAG[1]}
        VNUM3: ${IMAGE_TAG[2]}

        if: ${{ CURRENT_VERSION == v1.0.0 }}
        
        VNUM4: VNUM2+1
        VNUM5: VNUM3+1

        IMAGE_TAG: VNUM1+VNUM4+VNUM5
        
                                   
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo $ECR_REGISTRY
        echo $ECR_REPOSITORY
        echo $IMAGE_TAG
        
